# Generated by Django 2.0.8 on 2018-08-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlet', models.CharField(max_length=64)),
                ('display_from', models.DateTimeField(blank=True, null=True)),
                ('display_to', models.DateTimeField(blank=True, null=True)),
                ('purpose', models.CharField(choices=[('NOTICE', 'Notice')], max_length=12)),
                ('heading', models.CharField(blank=True, max_length=256)),
                ('body', models.TextField()),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
    ]
