# Generated by Django 2.0.8 on 2018-08-14 11:49

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='body',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
