# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentgroups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mslstudentgroup',
            old_name='msl_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='mslstudentgroup',
            old_name='msl_image',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='mslstudentgroup',
            old_name='msl_image_url',
            new_name='logo_url',
        ),
        migrations.AddField(
            model_name='mslstudentgroup',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mslstudentgroup',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='msl_group', to='studentgroups.StudentGroup'),
        ),
    ]
