# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentgroups', '0003_auto_20170703_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mslstudentgroup',
            name='link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mslstudentgroup',
            name='logo_url',
            field=models.URLField(default=''),
        ),
    ]
