# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matte', '0002_remoteimage'),
        ('studentgroups', '0004_auto_20170703_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='is_prospective',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='link',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matte.MatteImage'),
        ),
    ]
