# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentgroups', '0005_auto_20170905_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mslstudentgroup',
            name='logo_url',
            field=models.TextField(default=''),
        ),
    ]
