# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentgroups', '0006_auto_20170905_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='link',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matte.MatteImage'),
        ),
    ]
