# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentgroups', '0007_auto_20170908_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='AwardAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='GroupAwarded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentgroups.Award')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentgroups.StudentGroup')),
            ],
        ),
        migrations.AddField(
            model_name='award',
            name='authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentgroups.AwardAuthority'),
        ),
    ]
