# Generated by Django 2.0.2 on 2018-03-01 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentgroups', '0009_auto_20171031_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mslstudentgroup',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matte.MatteImage'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matte.MatteImage'),
        ),
    ]
