# Generated by Django 2.0.2 on 2018-05-01 11:43

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studentgroups', '0012_start_again_20180501_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AwardAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name': 'Award Authority',
                'verbose_name_plural': 'Award Authorities',
            },
        ),
        migrations.CreateModel(
            name='AwardPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('display_name', models.CharField(max_length=128)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentgroups.AwardAuthority')),
            ],
            options={
                'verbose_name': 'Award Period',
                'verbose_name_plural': 'Award Periods',
            },
        ),
        migrations.CreateModel(
            name='GroupAwarded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(default=0)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentgroups.Award')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentgroups.StudentGroup')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentgroups.AwardPeriod')),
            ],
        ),
        migrations.AlterModelOptions(
            name='mslstudentgroup',
            options={'verbose_name': 'MSL Student Group', 'verbose_name_plural': 'MSL Student Groups'},
        ),
        migrations.AlterModelOptions(
            name='mslstudentgroupcategory',
            options={'verbose_name': 'MSL Student Group Category', 'verbose_name_plural': 'MSL Student Group Categories'},
        ),
        migrations.AddField(
            model_name='award',
            name='authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentgroups.AwardAuthority'),
        ),
        migrations.AlterUniqueTogether(
            name='groupawarded',
            unique_together={('group', 'award', 'period', 'grade')},
        ),
    ]
