# Generated by Django 2.0.2 on 2018-05-10 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentgroups', '0013_auto_20180501_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupawarded',
            options={'verbose_name': 'Group Award', 'verbose_name_plural': 'Group Awards'},
        ),
    ]
