# Generated by Django 2.0.5 on 2018-06-21 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentgroups', '0014_auto_20180510_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='slug',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupawarded',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='studentgroups.StudentGroup'),
        ),
    ]
