# Generated by Django 2.0.5 on 2018-06-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentgroups', '0015_auto_20180621_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='slug',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
