# Generated by Django 2.0.5 on 2018-06-22 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentgroups', '0017_award_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='icon',
            field=models.CharField(choices=[('community', 'LeafCommunity'), ('development', 'LeafDevelopment'), ('social', 'LeafSocial'), ('student-voice', 'LeafStudentVoice'), ('team-sussex', 'LeafTeamSussex'), ('communications', 'LeafCommunications'), ('fundraising', 'LeafFundraising'), ('inclusivity', 'LeafInclusivity')], default='community', max_length=24),
        ),
        migrations.AlterField(
            model_name='groupawarded',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded', to='studentgroups.AwardPeriod'),
        ),
    ]
