# Generated by Django 2.0.5 on 2018-07-02 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentgroups', '0018_auto_20180622_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentgroup',
            options={'ordering': ['name']},
        ),
    ]
