# Generated by Django 2.0.8 on 2018-08-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentgroups', '0019_auto_20180628_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
