# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(unique=True)),
                ('matte_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matte.MatteImage')),
            ],
        ),
    ]
