# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matte', '0003_auto_20170912_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageExternalMetadata',
            fields=[
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='external_metadata', serialize=False, to='matte.MatteImage')),
                ('last_label_request_time', models.DateTimeField(blank=True, null=True)),
                ('last_label_request_status', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageLabelThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matte.MatteImage')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matte.ImageLabel')),
            ],
        ),
        migrations.AddField(
            model_name='matteimage',
            name='labels',
            field=models.ManyToManyField(through='matte.ImageLabelThrough', to='matte.ImageLabel'),
        ),
    ]
