# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matte', '0005_auto_20170913_1304'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imagelabelthrough',
            unique_together=set([('image', 'label')]),
        ),
    ]
