# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matte', '0006_auto_20170913_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageexternalmetadata',
            name='last_label_request_status',
            field=models.CharField(default='NA', max_length=8),
        ),
    ]
