# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matte', '0007_auto_20170913_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='matteimage',
            name='internal_source',
            field=models.IntegerField(choices=[(100, 'Default'), (400, 'Book Market - Listing')], default=100),
        ),
    ]
