# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailChimpList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailchimp_list_id', models.CharField(max_length=40)),
                ('enabled', models.BooleanField(default=True)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
