# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterResumeToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=255)),
                ('continuation_token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='mailchimplist',
            options={'verbose_name': 'MailChimp List'},
        ),
        migrations.AddField(
            model_name='newsletterresumetoken',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletters.MailChimpList'),
        ),
    ]
