# Generated by Django 2.0.2 on 2018-04-11 13:32

from django.db import migrations, models
import django.db.models.deletion
import falmer.content.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matte', '0009_auto_20180406_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Display name of the company offering the deal', max_length=255)),
                ('company_website', models.URLField(blank=True, default='')),
                ('deal_tag', models.CharField(help_text='The deal itself, "40%", "By one get one free", etc', max_length=255)),
                ('main', wagtail.core.fields.StreamField((('text', wagtail.core.blocks.StructBlock((('value', wagtail.core.blocks.RichTextBlock()),))), ('image', wagtail.core.blocks.StructBlock((('image', falmer.content.blocks.FalmerImageChooserBlock(required=True)), ('alternative_title', wagtail.core.blocks.CharBlock(required=False)), ('caption', wagtail.core.blocks.CharBlock(required=False))))), ('callout', wagtail.core.blocks.StructBlock((('value', wagtail.core.blocks.StructBlock((('value', wagtail.core.blocks.RichTextBlock()),))), ('variant', wagtail.core.blocks.ChoiceBlock(choices=[('info', 'Info'), ('warning', 'Warning'), ('alert', 'Alert')], label='Variant')))))), blank=True, help_text='Any additional information about this deal')),
            ],
        ),
        migrations.CreateModel(
            name='OfferCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Offer Category',
                'verbose_name_plural': 'Offer Categories',
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.OfferCategory'),
        ),
        migrations.AddField(
            model_name='offer',
            name='company_logo',
            field=models.ForeignKey(blank=True, help_text='Companies logo displayed next to the offer', null=True, on_delete=django.db.models.deletion.SET_NULL, to='matte.MatteImage'),
        ),
    ]
