# Generated by Django 2.0.5 on 2018-06-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
