# Generated by Django 2.0.8 on 2018-09-27 14:24

from django.db import migrations
import falmer.content.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0005_auto_20180818_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='main',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.StructBlock([('value', falmer.content.blocks.RichTextWithExpandedContent(features=['h2', 'bold', 'italic', 'ol', 'ul', 'hr', 'link']))])), ('image', wagtail.core.blocks.StructBlock([('image', falmer.content.blocks.FalmerImageChooserBlock(required=True)), ('alternative_title', wagtail.core.blocks.CharBlock(required=False)), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('callout', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.TextBlock()), ('variant', wagtail.core.blocks.ChoiceBlock(choices=[('info', 'Info'), ('alert', 'Alert')], label='Variant'))]))], blank=True, help_text='Any additional information about this deal'),
        ),
    ]
