# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0002_knowledgebaseroot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HowToPage',
            new_name='GuidePage',
        ),
    ]
