# Generated by Django 2.0.5 on 2018-07-02 13:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('kb', '0005_auto_20180123_1356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReferencePage',
            new_name='KBReferencePage',
        ),
    ]
