# Generated by Django 2.2.4 on 2019-10-14 13:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentcodeauthorisation',
            name='additional_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consentcodeauthorisation',
            name='code',
            field=models.CharField(default={}, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consentcodeform',
            name='additional_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
