# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-21 19:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slack_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
