# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-17 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falmer_auth', '0002_auto_20170415_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falmeruser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
