# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-21 19:45
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_sectioncontentpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectioncontentpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('section', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('body', wagtail.wagtailcore.blocks.StreamBlock((('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()),)))))),)),
        ),
        migrations.AlterField(
            model_name='sectioncontentpage',
            name='sidebar_body',
            field=wagtail.wagtailcore.fields.StreamField((('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('contact', wagtail.wagtailcore.blocks.StructBlock((('body', wagtail.wagtailcore.blocks.TextBlock()), ('name', wagtail.wagtailcore.blocks.CharBlock()), ('email', wagtail.wagtailcore.blocks.EmailBlock())))))),
        ),
    ]
