# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 13:56
from __future__ import unicode_literals

import falmer.content.models
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matte', '0001_initial'),
        ('content', '0003_auto_20170421_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMemberSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('office_phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('job_description', wagtail.core.fields.RichTextField()),
                ('office_location', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='matte.MatteImage')),
            ],
        ),
        migrations.AddField(
            model_name='staffpage',
            name='body',
            field=wagtail.core.fields.StreamField((('staff_list', wagtail.core.blocks.StructBlock((('body', wagtail.core.blocks.ListBlock(wagtail.core.blocks.ChooserBlock(required=falmer.content.models.StaffMemberSnippet))),))),), default=''),
            preserve_default=False,
        ),
    ]
