# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-29 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import falmer.content.models.selection_grid
import falmer.content.models.staff
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('content', '0004_auto_20170424_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionGridPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField((('grid', wagtail.core.blocks.ListBlock(falmer.content.models.selection_grid.GridItem)),))),
                ('show_heading_hero', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='staffpage',
            name='body',
            field=wagtail.core.fields.StreamField((('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('staff_list', wagtail.core.blocks.StructBlock((('heading', wagtail.core.blocks.CharBlock()), ('body', wagtail.core.blocks.ListBlock(falmer.content.models.staff.StaffMemberChooser(falmer.content.models.staff.StaffMemberSnippet)))))))),
        ),
    ]
