# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 10:43
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20170529_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectiongridpage',
            name='hero',
            field=wagtail.core.fields.StreamField((('heading', wagtail.core.blocks.CharBlock(required=True)),), default={}),
            preserve_default=False,
        ),
    ]
