# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matte', '0001_initial'),
        ('content', '0006_selectiongridpage_hero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectiongridpage',
            name='hero',
        ),
        migrations.AddField(
            model_name='selectiongridpage',
            name='heading_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='matte.MatteImage'),
        ),
    ]
