# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 15:19
from __future__ import unicode_literals

from django.db import migrations
import falmer.content.blocks
import falmer.content.models.selection_grid
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20170530_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectiongridpage',
            name='heading_image',
        ),
        migrations.RemoveField(
            model_name='selectiongridpage',
            name='show_heading_hero',
        ),
        migrations.AlterField(
            model_name='selectiongridpage',
            name='body',
            field=wagtail.core.fields.StreamField((('heading_hero', wagtail.core.blocks.StructBlock((('heading', wagtail.core.blocks.CharBlock(help_text='Leave empty to use the page title', required=False)), ('image', falmer.content.blocks.ImageBlock())))), ('selection_grid', wagtail.core.blocks.ListBlock(falmer.content.models.selection_grid.GridItem)))),
        ),
    ]
