# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-15 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matte', '0001_initial'),
        ('content', '0008_auto_20170530_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioncontentpage',
            name='heading_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matte.MatteImage'),
        ),
    ]
