# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-22 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import falmer.content.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matte', '0001_initial'),
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('content', '0009_sectioncontentpage_heading_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficerOverviewPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('role', models.CharField(max_length=255)),
                ('role_description', wagtail.core.fields.RichTextField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('manifesto_tagline', models.CharField(max_length=255)),
                ('manifesto_overview', wagtail.core.fields.RichTextField()),
                ('twitter_username', models.CharField(max_length=30)),
                ('pledges', wagtail.core.fields.StreamField((('pledges', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(required=True)), ('body', wagtail.core.blocks.RichTextBlock(required=True)), ('image', falmer.content.blocks.ImageBlock()), ('status', wagtail.core.blocks.ChoiceBlock(choices=[('in_progress', 'In Progress'), ('done', 'Done'), ('blank', 'Blank')]))))),))),
                ('officer_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matte.MatteImage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
