# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-22 13:45
from __future__ import unicode_literals

from django.db import migrations
import falmer.content.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_officeroverviewpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeroverviewpage',
            name='pledges',
            field=wagtail.wagtailcore.fields.StreamField((('pledge', wagtail.wagtailcore.blocks.StructBlock((('title', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('body', wagtail.wagtailcore.blocks.RichTextBlock(required=True)), ('image', falmer.content.blocks.ImageBlock()), ('status', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('in_progress', 'In Progress'), ('done', 'Done'), ('blank', 'Blank')]))))),)),
        ),
    ]
