# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import falmer.content.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0039_collectionviewrestriction'),
        ('content', '0011_auto_20170622_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('full_time_officers', wagtail.wagtailcore.fields.StreamField((('title', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('subtitle', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('image', falmer.content.blocks.ImageBlock())))),
                ('part_time_officers', wagtail.wagtailcore.fields.StreamField((('title', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('subtitle', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('image', falmer.content.blocks.ImageBlock())))),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
