# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 11:13
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_freshers17contentpage_freshers17guidespage_freshers17homepage_freshers17listicle_freshers17whatson'),
    ]

    operations = [
        migrations.AddField(
            model_name='freshers17listicle',
            name='body',
            field=wagtail.core.fields.StreamField((('item', wagtail.core.blocks.StructBlock((('title', wagtail.core.blocks.CharBlock(required=True)), ('body', wagtail.core.blocks.RichTextBlock())))),), default=''),
            preserve_default=False,
        ),
    ]
