# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 10:50
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_freshers17listicle_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmembersnippet',
            name='job_description',
            field=wagtail.core.fields.RichTextField(blank=True, default=''),
        ),
    ]
