# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('content', '0017_auto_20171017_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freshers17contentpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='freshers17guidespage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='freshers17homepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='freshers17listicle',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='freshers17whatson',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='Freshers17ContentPage',
        ),
        migrations.DeleteModel(
            name='Freshers17GuidesPage',
        ),
        migrations.DeleteModel(
            name='Freshers17HomePage',
        ),
        migrations.DeleteModel(
            name='Freshers17Listicle',
        ),
        migrations.DeleteModel(
            name='Freshers17WhatsOn',
        ),
    ]
