# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import falmer.content.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_offerspage_singleofferpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Offer Category',
                'verbose_name_plural': 'Offer Categories',
            },
        ),
        migrations.AlterField(
            model_name='singleofferpage',
            name='company_logo',
            field=models.ForeignKey(blank=True, help_text='Companies logo displayed next to the offer', null=True, on_delete=django.db.models.deletion.CASCADE, to='matte.MatteImage'),
        ),
        migrations.AlterField(
            model_name='singleofferpage',
            name='company_name',
            field=models.CharField(help_text='Display name of the company offering the deal', max_length=255),
        ),
        migrations.AlterField(
            model_name='singleofferpage',
            name='deal_tag',
            field=models.CharField(help_text='The deal itself, "40%", "By one get one free", etc', max_length=255),
        ),
        migrations.AlterField(
            model_name='singleofferpage',
            name='main',
            field=wagtail.core.fields.StreamField((('text', wagtail.core.blocks.StructBlock((('value', wagtail.core.blocks.RichTextBlock()),))), ('image', wagtail.core.blocks.StructBlock((('image', falmer.content.blocks.FalmerImageChooserBlock(required=True)), ('alternative_title', wagtail.core.blocks.CharBlock(required=False)), ('caption', wagtail.core.blocks.CharBlock(required=False))))), ('callout', wagtail.core.blocks.StructBlock((('value', wagtail.core.blocks.StructBlock((('value', wagtail.core.blocks.RichTextBlock()),))), ('variant', wagtail.core.blocks.ChoiceBlock(choices=[('info', 'Info'), ('warning', 'Warning'), ('alert', 'Alert')], label='Variant')))))), blank=True, help_text='Any additional information about this deal'),
        ),
        migrations.AddField(
            model_name='singleofferpage',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='content.OfferCategory'),
            preserve_default=False,
        ),
    ]
