# Generated by Django 2.0.2 on 2018-03-01 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_auto_20180124_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleofferpage',
            name='company_logo',
            field=models.ForeignKey(blank=True, help_text='Companies logo displayed next to the offer', null=True, on_delete=django.db.models.deletion.SET_NULL, to='matte.MatteImage'),
        ),
    ]
