# Generated by Django 2.0.2 on 2018-03-12 15:52

from django.db import migrations, models
import falmer.content.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_auto_20180301_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioncontentpage',
            name='heading_image_as_hero',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sectioncontentpage',
            name='body',
            field=wagtail.core.fields.StreamField((('section', wagtail.core.blocks.StructBlock((('heading', wagtail.core.blocks.CharBlock(required=True)), ('heading_image', falmer.content.blocks.FalmerImageChooserBlock()), ('body', wagtail.core.blocks.StreamBlock((('paragraph', falmer.content.blocks.RichTextWithExpandedContent()),)))))),)),
        ),
    ]
