# Generated by Django 2.0.2 on 2018-04-11 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('content', '0025_auto_20180406_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerspage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='singleofferpage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='singleofferpage',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='singleofferpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='OfferCategory',
        ),
        migrations.DeleteModel(
            name='OffersPage',
        ),
        migrations.DeleteModel(
            name='SingleOfferPage',
        ),
    ]
