# Generated by Django 2.0.5 on 2018-07-02 20:38

from django.db import migrations
import falmer.content.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_answerpage_contentrootpage_detailedguidepage_detailedguidesectionpage_referencepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerpage',
            name='content',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.RichTextBlock())])), ('callout', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.RichTextBlock())])), ('variant', wagtail.core.blocks.ChoiceBlock(choices=[('info', 'Info'), ('warning', 'Warning'), ('alert', 'Alert')], label='Variant'))])), ('image', wagtail.core.blocks.StructBlock([('image', falmer.content.blocks.FalmerImageChooserBlock(required=True)), ('alternative_title', wagtail.core.blocks.CharBlock(required=False)), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('button_group_links', wagtail.core.blocks.StreamBlock([('internal_link', wagtail.core.blocks.StructBlock([('link', falmer.content.blocks.FalmerPageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=False))], label='Internal page')), ('external_link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.URLBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('target', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Open link in'), ('_self', 'Same window'), ('_blank', 'New window')], help_text='Open link in'))], label='External Page'))]))], blank=True, null=True, verbose_name='Main Content'),
        ),
        migrations.AddField(
            model_name='detailedguidesectionpage',
            name='content',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.RichTextBlock())])), ('callout', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.RichTextBlock())])), ('variant', wagtail.core.blocks.ChoiceBlock(choices=[('info', 'Info'), ('warning', 'Warning'), ('alert', 'Alert')], label='Variant'))])), ('image', wagtail.core.blocks.StructBlock([('image', falmer.content.blocks.FalmerImageChooserBlock(required=True)), ('alternative_title', wagtail.core.blocks.CharBlock(required=False)), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('button_group_links', wagtail.core.blocks.StreamBlock([('internal_link', wagtail.core.blocks.StructBlock([('link', falmer.content.blocks.FalmerPageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=False))], label='Internal page')), ('external_link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.URLBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('target', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Open link in'), ('_self', 'Same window'), ('_blank', 'New window')], help_text='Open link in'))], label='External Page'))]))], blank=True, null=True, verbose_name='Main Content'),
        ),
        migrations.AddField(
            model_name='referencepage',
            name='content',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.RichTextBlock())])), ('callout', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.RichTextBlock())])), ('variant', wagtail.core.blocks.ChoiceBlock(choices=[('info', 'Info'), ('warning', 'Warning'), ('alert', 'Alert')], label='Variant'))])), ('image', wagtail.core.blocks.StructBlock([('image', falmer.content.blocks.FalmerImageChooserBlock(required=True)), ('alternative_title', wagtail.core.blocks.CharBlock(required=False)), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('button_group_links', wagtail.core.blocks.StreamBlock([('internal_link', wagtail.core.blocks.StructBlock([('link', falmer.content.blocks.FalmerPageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=False))], label='Internal page')), ('external_link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.URLBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('target', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Open link in'), ('_self', 'Same window'), ('_blank', 'New window')], help_text='Open link in'))], label='External Page'))]))], blank=True, null=True, verbose_name='Main Content'),
        ),
    ]
