# Generated by Django 2.0.5 on 2018-07-04 10:03

from django.db import migrations
import falmer.content.blocks
import falmer.content.models.staff
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_auto_20180703_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailedguidesectionpage',
            name='related_links',
        ),
        migrations.RemoveField(
            model_name='detailedguidesectionpage',
            name='staff_owners',
        ),
        migrations.AddField(
            model_name='detailedguidepage',
            name='related_links',
            field=wagtail.core.fields.StreamField([('link_section', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(required=False)), ('links', wagtail.core.blocks.StreamBlock([('internal_link', wagtail.core.blocks.StructBlock([('link', falmer.content.blocks.FalmerPageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=False))], label='Internal page')), ('external_link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.URLBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('target', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Open link in'), ('_self', 'Same window'), ('_blank', 'New window')], help_text='Open link in'))], label='External Page'))]))]))], default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailedguidepage',
            name='staff_owners',
            field=wagtail.core.fields.StreamField([('staff_member', falmer.content.models.staff.StaffMemberChooser(falmer.content.models.staff.StaffMemberSnippet))], default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answerpage',
            name='content',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.RichTextBlock(features=['h2', 'bold', 'italic', 'ol', 'ul', 'hr']))])), ('alert_text', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.RichTextBlock(features=['italic']))])), ('inset_text', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.RichTextBlock(features=['italic']))])), ('image', wagtail.core.blocks.StructBlock([('image', falmer.content.blocks.FalmerImageChooserBlock(required=True)), ('alternative_title', wagtail.core.blocks.CharBlock(required=False)), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('button_group_links', wagtail.core.blocks.StreamBlock([('internal_link', wagtail.core.blocks.StructBlock([('link', falmer.content.blocks.FalmerPageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=False))], label='Internal page')), ('external_link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.URLBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('target', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Open link in'), ('_self', 'Same window'), ('_blank', 'New window')], help_text='Open link in'))], label='External Page'))])), ('start_button', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('page', falmer.content.blocks.FalmerPageChooserBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False))]))], blank=True, null=True, verbose_name='Main Content'),
        ),
        migrations.AlterField(
            model_name='detailedguidesectionpage',
            name='content',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.RichTextBlock(features=['h2', 'bold', 'italic', 'ol', 'ul', 'hr']))])), ('callout', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.TextBlock()), ('variant', wagtail.core.blocks.ChoiceBlock(choices=[('info', 'Info'), ('alert', 'Alert')], label='Variant'))])), ('alert_text', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.RichTextBlock(features=['italic']))])), ('inset_text', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.RichTextBlock(features=['italic']))])), ('image', wagtail.core.blocks.StructBlock([('image', falmer.content.blocks.FalmerImageChooserBlock(required=True)), ('alternative_title', wagtail.core.blocks.CharBlock(required=False)), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('button_group_links', wagtail.core.blocks.StreamBlock([('internal_link', wagtail.core.blocks.StructBlock([('link', falmer.content.blocks.FalmerPageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=False))], label='Internal page')), ('external_link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.URLBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('target', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Open link in'), ('_self', 'Same window'), ('_blank', 'New window')], help_text='Open link in'))], label='External Page'))]))], blank=True, null=True, verbose_name='Main Content'),
        ),
        migrations.AlterField(
            model_name='referencepage',
            name='content',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.RichTextBlock(features=['h2', 'bold', 'italic', 'ol', 'ul', 'hr']))])), ('callout', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.TextBlock()), ('variant', wagtail.core.blocks.ChoiceBlock(choices=[('info', 'Info'), ('alert', 'Alert')], label='Variant'))])), ('alert_text', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.RichTextBlock(features=['italic']))])), ('inset_text', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.RichTextBlock(features=['italic']))])), ('image', wagtail.core.blocks.StructBlock([('image', falmer.content.blocks.FalmerImageChooserBlock(required=True)), ('alternative_title', wagtail.core.blocks.CharBlock(required=False)), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('button_group_links', wagtail.core.blocks.StreamBlock([('internal_link', wagtail.core.blocks.StructBlock([('link', falmer.content.blocks.FalmerPageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=False))], label='Internal page')), ('external_link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.URLBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('target', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Open link in'), ('_self', 'Same window'), ('_blank', 'New window')], help_text='Open link in'))], label='External Page'))]))], blank=True, null=True, verbose_name='Main Content'),
        ),
    ]
