# Generated by Django 2.0.8 on 2018-08-12 14:06

from django.db import migrations, models
import django.db.models.deletion
import falmer.content.blocks
import re
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('matte', '0010_matteimage_file_hash'),
        ('events', '0028_auto_20180730_1310'),
        ('content', '0033_basiccontentpage_officersindex_stubpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutletIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('preamble', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.RichTextBlock(features=['h2', 'bold', 'italic', 'ol', 'ul', 'hr']))]))])),
            ],
            options={
                'abstract': False,
            },
            bases=('content.page',),
        ),
        migrations.CreateModel(
            name='OutletPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('main', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.RichTextBlock(features=['h2', 'bold', 'italic', 'ol', 'ul', 'hr']))]))], blank=True, null=True, verbose_name='Main Content')),
                ('opening_times', wagtail.core.fields.StreamField([('opening_times', wagtail.core.blocks.StructBlock([('special_tag', wagtail.core.blocks.CharBlock(help_text='Add a little label if these are unusual opening times, for instance holidays', required=False)), ('times', wagtail.core.blocks.ListBlock(wagtail.core.blocks.RegexBlock(re.compile('[Mo|Tu|We|Th|Fr|Sa|Su|\\-|,]+ [0-9]{2}:[0-9]{2}-[0-9]{2}:[0-9]{2}'), help_text='Please see our docs for opening times formatting', required=True))), ('enabled', wagtail.core.blocks.BooleanBlock(help_text='Disable for non-used opening times, for instance holidays', required=False))]))])),
                ('menu', wagtail.core.fields.StreamField([('document_link', wagtail.core.blocks.StructBlock([('link', falmer.content.blocks.FalmerPageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=False))]))])),
                ('deals', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.RichTextBlock(features=['h2', 'bold', 'italic', 'ol', 'ul', 'hr']))]))])),
                ('hero_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matte.MatteImage')),
                ('linked_venue', models.ForeignKey(blank=True, help_text="Link this outlet with a venue's events", null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.Venue')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.page',),
        ),
    ]
