# Generated by Django 2.0.8 on 2018-08-14 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0040_page_draft_title'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailmenus', '0022_auto_20170913_2125'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('content', '0034_outletindexpage_outletpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='KBCategoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.page',),
        ),
        migrations.RenameModel(
            old_name='ContentRootPage',
            new_name='KBRootPage',
        ),
    ]
