# Generated by Django 2.0.8 on 2018-08-14 15:06

from django.db import migrations
import falmer.content.blocks
import falmer.content.models.staff
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_auto_20180814_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerpage',
            name='related_links',
            field=wagtail.core.fields.StreamField([('link_section', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(required=False)), ('links', wagtail.core.blocks.StreamBlock([('internal_link', wagtail.core.blocks.StructBlock([('link', falmer.content.blocks.FalmerPageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=False))], label='Internal page')), ('external_link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.URLBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('target', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Open link in'), ('_self', 'Same window'), ('_blank', 'New window')], help_text='Open link in'))], label='External Page'))]))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='answerpage',
            name='staff_owners',
            field=wagtail.core.fields.StreamField([('staff_member', falmer.content.models.staff.StaffMemberChooser(falmer.content.models.staff.StaffMemberSnippet))], blank=True),
        ),
        migrations.AlterField(
            model_name='detailedguidepage',
            name='related_links',
            field=wagtail.core.fields.StreamField([('link_section', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(required=False)), ('links', wagtail.core.blocks.StreamBlock([('internal_link', wagtail.core.blocks.StructBlock([('link', falmer.content.blocks.FalmerPageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=False))], label='Internal page')), ('external_link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.URLBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('target', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Open link in'), ('_self', 'Same window'), ('_blank', 'New window')], help_text='Open link in'))], label='External Page'))]))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='detailedguidepage',
            name='staff_owners',
            field=wagtail.core.fields.StreamField([('staff_member', falmer.content.models.staff.StaffMemberChooser(falmer.content.models.staff.StaffMemberSnippet))], blank=True),
        ),
        migrations.AlterField(
            model_name='referencepage',
            name='related_links',
            field=wagtail.core.fields.StreamField([('link_section', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(required=False)), ('links', wagtail.core.blocks.StreamBlock([('internal_link', wagtail.core.blocks.StructBlock([('link', falmer.content.blocks.FalmerPageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=False))], label='Internal page')), ('external_link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.URLBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('target', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Open link in'), ('_self', 'Same window'), ('_blank', 'New window')], help_text='Open link in'))], label='External Page'))]))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='referencepage',
            name='staff_owners',
            field=wagtail.core.fields.StreamField([('staff_member', falmer.content.models.staff.StaffMemberChooser(falmer.content.models.staff.StaffMemberSnippet))], blank=True),
        ),
    ]
