# Generated by Django 2.0.8 on 2018-09-11 15:00

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0039_auto_20180911_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletpage',
            name='menu',
            field=wagtail.core.fields.StreamField([('document_link', wagtail.core.blocks.StructBlock([('link', wagtail.documents.blocks.DocumentChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=False))]))]),
        ),
    ]
