# Generated by Django 2.0.8 on 2018-09-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailmenus', '0022_auto_20170913_2125'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('content', '0040_auto_20180911_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffdepartment',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='department',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='staffsection',
            name='page_ptr',
        ),
        migrations.AlterModelOptions(
            name='staffmembersnippet',
            options={'verbose_name': 'Job Role', 'verbose_name_plural': 'Job Roles'},
        ),
        migrations.AlterField(
            model_name='kbcategorypage',
            name='page_icon',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='staffmembersnippet',
            name='job_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='StaffDepartment',
        ),
        migrations.DeleteModel(
            name='StaffMember',
        ),
        migrations.DeleteModel(
            name='StaffSection',
        ),
    ]
