# Generated by Django 2.0.8 on 2018-09-12 13:04

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0041_auto_20180912_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbrootpage',
            name='introduction',
            field=wagtail.core.fields.RichTextField(blank=True, default=''),
        ),
    ]
