# Generated by Django 2.0.8 on 2018-09-28 11:23

from django.db import migrations, models
import django.db.models.deletion
import falmer.content.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('matte', '0010_matteimage_file_hash'),
        ('content', '0043_auto_20180927_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('preamble', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.StructBlock([('value', falmer.content.blocks.RichTextWithExpandedContent(features=['h2', 'bold', 'italic', 'ol', 'ul', 'hr', 'link']))]))])),
            ],
            options={
                'abstract': False,
            },
            bases=('content.page',),
        ),
        migrations.CreateModel(
            name='SchemePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('social_facebook_url', models.URLField(blank=True, default='')),
                ('social_twitter_handle', models.CharField(blank=True, default='', max_length=128)),
                ('social_snapchat_handle', models.CharField(blank=True, default='', max_length=128)),
                ('social_instagram_handle', models.CharField(blank=True, default='', max_length=128)),
                ('social_email_address', models.EmailField(blank=True, default='', max_length=254)),
                ('main', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.StructBlock([('value', falmer.content.blocks.RichTextWithExpandedContent(features=['h2', 'bold', 'italic', 'ol', 'ul', 'hr', 'link']))]))], blank=True, null=True, verbose_name='Main Content')),
                ('sidebar_cards', wagtail.core.fields.StreamField([('sidebar_card', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(required=True)), ('content', wagtail.core.blocks.StreamBlock([('text', wagtail.core.blocks.StructBlock([('value', falmer.content.blocks.RichTextWithExpandedContent(features=['h2', 'bold', 'italic', 'ol', 'ul', 'hr', 'link']))])), ('basic_button', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('page', falmer.content.blocks.FalmerPageChooserBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False))]))]))]))], blank=True)),
                ('hero_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matte.MatteImage')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.page', models.Model),
        ),
    ]
