# Generated by Django 2.0.8 on 2018-10-04 12:20

from django.db import migrations
import falmer.content.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0044_schemeindexpage_schemepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerpage',
            name='content',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.StructBlock([('value', falmer.content.blocks.RichTextWithExpandedContent(features=['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'hr', 'link']))])), ('alert_text', wagtail.core.blocks.StructBlock([('value', falmer.content.blocks.RichTextWithExpandedContent(features=['italic']))])), ('inset_text', wagtail.core.blocks.StructBlock([('value', falmer.content.blocks.RichTextWithExpandedContent(features=['italic']))])), ('image', wagtail.core.blocks.StructBlock([('image', falmer.content.blocks.FalmerImageChooserBlock(required=True)), ('alternative_title', wagtail.core.blocks.CharBlock(required=False)), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('button_group_links', wagtail.core.blocks.StreamBlock([('internal_link', wagtail.core.blocks.StructBlock([('link', falmer.content.blocks.FalmerPageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=False))], label='Internal page')), ('external_link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.URLBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('target', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Open link in'), ('_self', 'Same window'), ('_blank', 'New window')], help_text='Open link in'))], label='External Page'))])), ('start_button', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('page', falmer.content.blocks.FalmerPageChooserBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False))]))], blank=True, null=True, verbose_name='Main Content'),
        ),
        migrations.AlterField(
            model_name='basiccontentpage',
            name='content',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.StructBlock([('value', falmer.content.blocks.RichTextWithExpandedContent(features=['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'hr', 'link']))])), ('callout', wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.TextBlock()), ('variant', wagtail.core.blocks.ChoiceBlock(choices=[('info', 'Info'), ('alert', 'Alert')], label='Variant'))])), ('alert_text', wagtail.core.blocks.StructBlock([('value', falmer.content.blocks.RichTextWithExpandedContent(features=['italic']))])), ('inset_text', wagtail.core.blocks.StructBlock([('value', falmer.content.blocks.RichTextWithExpandedContent(features=['italic']))])), ('image', wagtail.core.blocks.StructBlock([('image', falmer.content.blocks.FalmerImageChooserBlock(required=True)), ('alternative_title', wagtail.core.blocks.CharBlock(required=False)), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('button_group_links', wagtail.core.blocks.StreamBlock([('internal_link', wagtail.core.blocks.StructBlock([('link', falmer.content.blocks.FalmerPageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=False))], label='Internal page')), ('external_link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.URLBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('target', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Open link in'), ('_self', 'Same window'), ('_blank', 'New window')], help_text='Open link in'))], label='External Page'))]))], blank=True, null=True, verbose_name='Main Content'),
        ),
        migrations.AlterField(
            model_name='detailedguidesectionpage',
            name='content',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.StructBlock([('value', falmer.content.blocks.RichTextWithExpandedContent(features=['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'hr', 'link']))])), ('alert_text', wagtail.core.blocks.StructBlock([('value', falmer.content.blocks.RichTextWithExpandedContent(features=['italic']))])), ('inset_text', wagtail.core.blocks.StructBlock([('value', falmer.content.blocks.RichTextWithExpandedContent(features=['italic']))])), ('image', wagtail.core.blocks.StructBlock([('image', falmer.content.blocks.FalmerImageChooserBlock(required=True)), ('alternative_title', wagtail.core.blocks.CharBlock(required=False)), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('button_group_links', wagtail.core.blocks.StreamBlock([('internal_link', wagtail.core.blocks.StructBlock([('link', falmer.content.blocks.FalmerPageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=False))], label='Internal page')), ('external_link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.URLBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('target', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Open link in'), ('_self', 'Same window'), ('_blank', 'New window')], help_text='Open link in'))], label='External Page'))]))], blank=True, null=True, verbose_name='Main Content'),
        ),
        migrations.AlterField(
            model_name='outletindexpage',
            name='preamble',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.StructBlock([('value', falmer.content.blocks.RichTextWithExpandedContent(features=['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'hr', 'link']))]))]),
        ),
        migrations.AlterField(
            model_name='outletpage',
            name='deals',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.StructBlock([('value', falmer.content.blocks.RichTextWithExpandedContent(features=['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'hr', 'link']))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='outletpage',
            name='main',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.StructBlock([('value', falmer.content.blocks.RichTextWithExpandedContent(features=['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'hr', 'link']))]))], blank=True, null=True, verbose_name='Main Content'),
        ),
        migrations.AlterField(
            model_name='referencepage',
            name='content',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.StructBlock([('value', falmer.content.blocks.RichTextWithExpandedContent(features=['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'hr', 'link']))])), ('alert_text', wagtail.core.blocks.StructBlock([('value', falmer.content.blocks.RichTextWithExpandedContent(features=['italic']))])), ('inset_text', wagtail.core.blocks.StructBlock([('value', falmer.content.blocks.RichTextWithExpandedContent(features=['italic']))])), ('image', wagtail.core.blocks.StructBlock([('image', falmer.content.blocks.FalmerImageChooserBlock(required=True)), ('alternative_title', wagtail.core.blocks.CharBlock(required=False)), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('button_group_links', wagtail.core.blocks.StreamBlock([('internal_link', wagtail.core.blocks.StructBlock([('link', falmer.content.blocks.FalmerPageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=False))], label='Internal page')), ('external_link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.URLBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('target', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Open link in'), ('_self', 'Same window'), ('_blank', 'New window')], help_text='Open link in'))], label='External Page'))]))], blank=True, null=True, verbose_name='Main Content'),
        ),
        migrations.AlterField(
            model_name='schemeindexpage',
            name='preamble',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.StructBlock([('value', falmer.content.blocks.RichTextWithExpandedContent(features=['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'hr', 'link']))]))]),
        ),
        migrations.AlterField(
            model_name='schemepage',
            name='main',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.StructBlock([('value', falmer.content.blocks.RichTextWithExpandedContent(features=['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'hr', 'link']))]))], blank=True, null=True, verbose_name='Main Content'),
        ),
        migrations.AlterField(
            model_name='schemepage',
            name='sidebar_cards',
            field=wagtail.core.fields.StreamField([('sidebar_card', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(required=True)), ('content', wagtail.core.blocks.StreamBlock([('text', wagtail.core.blocks.StructBlock([('value', falmer.content.blocks.RichTextWithExpandedContent(features=['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'hr', 'link']))])), ('basic_button', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('page', falmer.content.blocks.FalmerPageChooserBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False))]))]))]))], blank=True),
        ),
    ]
