# Generated by Django 2.2.2 on 2019-06-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0045_auto_20181004_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('page_data', models.TextField()),
                ('page_id', models.IntegerField()),
            ],
        ),
    ]
