# Generated by Django 2.2.2 on 2019-06-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0046_previewdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='previewdata',
            name='preview_method',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('EDIT', 'Edit'), ('CREATE', 'Create')], default='EDIT', max_length=6),
            preserve_default=False,
        ),
    ]
