# Generated by Django 2.2.2 on 2019-06-20 15:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0047_previewdata_preview_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previewdata',
            name='page_data',
        ),
        migrations.RemoveField(
            model_name='previewdata',
            name='page_id',
        ),
        migrations.AddField(
            model_name='previewdata',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
