# Generated by Django 2.2.2 on 2019-07-02 10:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0048_auto_20190620_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officeroverviewpage',
            name='manifesto_overview',
        ),
        migrations.RemoveField(
            model_name='officeroverviewpage',
            name='manifesto_tagline',
        ),
        migrations.AddField(
            model_name='officeroverviewpage',
            name='facebook_url',
            field=models.URLField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='officeroverviewpage',
            name='instagram_url',
            field=models.URLField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='officeroverviewpage',
            name='youtube_splash',
            field=models.URLField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='officeroverviewpage',
            name='twitter_username',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='previewdata',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
