# Generated by Django 2.2.3 on 2019-07-23 12:54

from django.db import migrations, models
import falmer.content.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0051_auto_20190704_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='freshershomepage',
            name='content',
            field=wagtail.core.fields.StreamField([('two_slice_component', wagtail.core.blocks.StructBlock([('menu_name', wagtail.core.blocks.CharBlock(required=True)), ('background_color', wagtail.core.blocks.CharBlock(max_length=7, required=True)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('description', wagtail.core.blocks.TextBlock(required=True)), ('col_one_title', wagtail.core.blocks.CharBlock(required=True)), ('col_one_content', wagtail.core.blocks.StreamBlock([('text', wagtail.core.blocks.StructBlock([('value', falmer.content.blocks.RichTextWithExpandedContent(features=['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'hr', 'link']))])), ('internal_link', wagtail.core.blocks.StructBlock([('link', falmer.content.blocks.FalmerPageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=False))])), ('external_link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.URLBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('target', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Open link in'), ('_self', 'Same window'), ('_blank', 'New window')], help_text='Open link in'))]))])), ('col_two_title', wagtail.core.blocks.CharBlock(required=True)), ('col_two_content', wagtail.core.blocks.StreamBlock([('text', wagtail.core.blocks.StructBlock([('value', falmer.content.blocks.RichTextWithExpandedContent(features=['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'hr', 'link']))])), ('internal_link', wagtail.core.blocks.StructBlock([('link', falmer.content.blocks.FalmerPageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=False))])), ('external_link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.URLBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('target', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Open link in'), ('_self', 'Same window'), ('_blank', 'New window')], help_text='Open link in'))]))]))])), ('profile_slice_component', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('description', wagtail.core.blocks.TextBlock(required=True)), ('menu_name', wagtail.core.blocks.CharBlock(required=True)), ('background_color', wagtail.core.blocks.CharBlock(max_length=7, required=True)), ('body', wagtail.core.blocks.StreamBlock([('text', wagtail.core.blocks.StructBlock([('value', falmer.content.blocks.RichTextWithExpandedContent(features=['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'hr', 'link']))])), ('internal_link', wagtail.core.blocks.StructBlock([('link', falmer.content.blocks.FalmerPageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=False))])), ('external_link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.URLBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('target', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Open link in'), ('_self', 'Same window'), ('_blank', 'New window')], help_text='Open link in'))]))])), ('image', wagtail.images.blocks.ImageChooserBlock()), ('image_caption', wagtail.core.blocks.CharBlock(required=True))]))], blank=True, null=True, verbose_name='Main Content'),
        ),
        migrations.AddField(
            model_name='freshershomepage',
            name='countdown_caption',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freshershomepage',
            name='countdown_target',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freshershomepage',
            name='hero_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
