# Generated by Django 2.2.3 on 2019-07-23 13:00

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0052_auto_20190723_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freshershomepage',
            name='hero_text',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
