# Generated by Django 2.2.3 on 2019-07-23 13:09

from django.db import migrations
import falmer.content.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0053_auto_20190723_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freshershomepage',
            name='content',
            field=wagtail.core.fields.StreamField([('two_slice_component', wagtail.core.blocks.StructBlock([('menu_name', wagtail.core.blocks.CharBlock(required=True)), ('background_color', wagtail.core.blocks.CharBlock(max_length=7, required=True)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('description', wagtail.core.blocks.TextBlock(required=True)), ('col_one_title', wagtail.core.blocks.CharBlock(required=True)), ('col_one_content', wagtail.core.blocks.StreamBlock([('text', wagtail.core.blocks.StructBlock([('value', falmer.content.blocks.RichTextWithExpandedContent(features=['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'hr', 'link']))])), ('internal_link', wagtail.core.blocks.StructBlock([('link', falmer.content.blocks.FalmerPageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=False))])), ('external_link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.URLBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('target', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Open link in'), ('_self', 'Same window'), ('_blank', 'New window')], help_text='Open link in'))]))])), ('col_two_title', wagtail.core.blocks.CharBlock(required=True)), ('col_two_content', wagtail.core.blocks.StreamBlock([('text', wagtail.core.blocks.StructBlock([('value', falmer.content.blocks.RichTextWithExpandedContent(features=['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'hr', 'link']))])), ('internal_link', wagtail.core.blocks.StructBlock([('link', falmer.content.blocks.FalmerPageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=False))])), ('external_link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.URLBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('target', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Open link in'), ('_self', 'Same window'), ('_blank', 'New window')], help_text='Open link in'))]))]))])), ('profile_slice_component', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('description', wagtail.core.blocks.TextBlock(required=True)), ('menu_name', wagtail.core.blocks.CharBlock(required=True)), ('background_color', wagtail.core.blocks.CharBlock(max_length=7, required=True)), ('body', wagtail.core.blocks.StreamBlock([('text', wagtail.core.blocks.StructBlock([('value', falmer.content.blocks.RichTextWithExpandedContent(features=['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'hr', 'link']))])), ('internal_link', wagtail.core.blocks.StructBlock([('link', falmer.content.blocks.FalmerPageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=False))])), ('external_link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.URLBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('target', wagtail.core.blocks.ChoiceBlock(choices=[('', 'Open link in'), ('_self', 'Same window'), ('_blank', 'New window')], help_text='Open link in'))]))])), ('image', wagtail.core.blocks.StructBlock([('image', falmer.content.blocks.FalmerImageChooserBlock(required=True)), ('alternative_title', wagtail.core.blocks.CharBlock(required=False)), ('caption', wagtail.core.blocks.CharBlock(required=False))]))]))], blank=True, null=True, verbose_name='Main Content'),
        ),
    ]
