# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 17:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matte', '0008_matteimage_internal_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('state', models.CharField(default='DRAFT', max_length=10)),
                ('listing_change_canary', models.IntegerField(default=0, editable=False)),
                ('listed_at', models.DateTimeField(null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('listing_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matte.MatteImage')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarket.Listing')),
            ],
        ),
        migrations.CreateModel(
            name='ListingSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarket.ListingSection'),
        ),
    ]
