# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='book_author',
            field=models.TextField(default=''),
        ),
    ]
