# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matte', '0008_matteimage_internal_source'),
        ('bookmarket', '0002_listing_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='listingimage',
            name='listing',
        ),
        migrations.AddField(
            model_name='listing',
            name='images',
            field=models.ManyToManyField(to='matte.MatteImage'),
        ),
        migrations.DeleteModel(
            name='ListingImage',
        ),
    ]
