# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 19:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmarket', '0003_auto_20180228_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingContactRequester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='contact_details',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listingcontactrequester',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarket.Listing'),
        ),
        migrations.AddField(
            model_name='listingcontactrequester',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='contact_requesters',
            field=models.ManyToManyField(through='bookmarket.ListingContactRequester', to=settings.AUTH_USER_MODEL),
        ),
    ]
