# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-01 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarket', '0004_auto_20180228_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
