# Generated by Django 2.2.9 on 2020-01-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarket', '0005_auto_20180301_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('UNLISTED', 'Unlisted'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=10),
        ),
    ]
