# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-10 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msl_event_link', models.CharField(max_length=255, unique=True)),
                ('social_facebook', models.URLField(blank=True, default='')),
                ('smart_location', models.CharField(blank=True, choices=[('ROOM_76', 'Room 76'), ('FALMER_BAR', 'Falmer Bar'), ('EAST_SLOPE', 'East Slope')], max_length=20, null=True)),
                ('featured_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matte.MatteImage')),
            ],
        ),
    ]
