# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-27 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSLEvent',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='events.Event')),
                ('disable_sync', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('has_tickets', models.BooleanField()),
                ('org_id', models.CharField(max_length=30)),
                ('org_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('url', models.URLField()),
                ('location', models.CharField(max_length=255)),
                ('msl_event_id', models.CharField(max_length=255)),
                ('body_html', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='msl_event_link',
        ),
        migrations.RemoveField(
            model_name='event',
            name='smart_location',
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='Untitled Event', max_length=255),
            preserve_default=False,
        ),
    ]
