# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170628_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='kicker',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='venue',
            name='website_link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
