# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170629_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
