# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=72)),
                ('website_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=72)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=72)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=72)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='alcohol',
            field=models.CharField(choices=[('AV', 'Soft drinks & alcohol available'), ('NO', 'No alcohol'), ('NF', 'Not alcohol focused')], default='NF', max_length=2),
        ),
        migrations.AddField(
            model_name='event',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='cost',
            field=models.CharField(choices=[('FREE', 'Free'), ('PAID', 'Paid'), ('NA', 'n/a')], default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='embargo_until',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_over_18_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='just_for_pgs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
        migrations.AddField(
            model_name='event',
            name='suitable_kids_families',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_level',
            field=models.CharField(choices=[('NA', 'Not applicable'), ('LA', 'Limited availability'), ('SO', 'Sold out')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='event',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.BrandingPeriod'),
        ),
        migrations.AddField(
            model_name='event',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Bundle'),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Category'),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Type'),
        ),
    ]
