# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20170817_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matte.MatteImage'),
        ),
        migrations.AlterField(
            model_name='event',
            name='kicker',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
