# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matte', '0002_remoteimage'),
        ('events', '0007_auto_20170817_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_data',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_type',
            field=models.CharField(choices=[('NA', 'Not applicable'), ('LA', 'Limited availability'), ('SO', 'Sold out')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='venue',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matte.MatteImage'),
        ),
        migrations.AddField(
            model_name='venue',
            name='short_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='body',
            field=wagtail.core.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_display',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
