# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20170821_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ticket_type',
            field=models.CharField(choices=[('NA', 'n/a'), ('NT', 'Native')], default='NA', max_length=2),
        ),
    ]
