# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20170821_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ticket_data',
            field=models.TextField(blank=True, default=''),
        ),
    ]
