# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20170905_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mslevent',
            name='image_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='mslevent',
            name='url',
            field=models.URLField(max_length=2000),
        ),
    ]
