# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='embargo_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
