# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentgroups', '0007_auto_20170908_1041'),
        ('events', '0014_auto_20171017_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='student_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentgroups.StudentGroup'),
        ),
    ]
