# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20171025_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingperiod',
            name='accent',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='brandingperiod',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, default=''),
        ),
    ]
