# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matte', '0007_auto_20170913_1321'),
        ('events', '0018_auto_20171128_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingperiod',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matte.MatteImage'),
        ),
        migrations.AddField(
            model_name='brandingperiod',
            name='logo_vector',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
