# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 15:00
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20171211_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingperiod',
            name='event_append',
            field=wagtail.core.fields.RichTextField(blank=True, default=''),
        ),
    ]
