# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20180112_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mslevent',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
