# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20180112_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mslevent',
            name='msl_event_id',
            field=models.IntegerField(),
        ),
    ]
