# Generated by Django 2.0.5 on 2018-06-28 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20180301_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mslevent',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='msl_event', serialize=False, to='events.Event'),
        ),
    ]
