# Generated by Django 2.0.7 on 2018-07-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_auto_20180730_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contains_flashing_lights',
            field=models.SmallIntegerField(choices=[(0, 'Not set/inherit'), (1, 'Negative'), (2, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='contains_flashing_lights_reasoning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='contains_loud_music',
            field=models.SmallIntegerField(choices=[(0, 'Not set/inherit'), (1, 'Negative'), (2, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='contains_loud_music_reasoning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='contains_low_light',
            field=models.SmallIntegerField(choices=[(0, 'Not set/inherit'), (1, 'Negative'), (2, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='contains_low_light_reasoning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='contains_uneven_ground',
            field=models.SmallIntegerField(choices=[(0, 'Not set/inherit'), (1, 'Negative'), (2, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='contains_uneven_ground_reasoning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='has_accessible_toilets',
            field=models.SmallIntegerField(choices=[(0, 'Not set/inherit'), (1, 'Negative'), (2, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='has_accessible_toilets_reasoning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='has_changing_facilities',
            field=models.SmallIntegerField(choices=[(0, 'Not set/inherit'), (1, 'Negative'), (2, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='has_changing_facilities_reasoning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='has_gender_neutral_toilets',
            field=models.SmallIntegerField(choices=[(0, 'Not set/inherit'), (1, 'Negative'), (2, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='has_gender_neutral_toilets_reasoning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='has_level_access',
            field=models.SmallIntegerField(choices=[(0, 'Not set/inherit'), (1, 'Negative'), (2, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='has_level_access_reasoning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='venue',
            name='contains_flashing_lights',
            field=models.SmallIntegerField(choices=[(0, 'Not set/inherit'), (1, 'Negative'), (2, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='venue',
            name='contains_flashing_lights_reasoning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='venue',
            name='contains_loud_music',
            field=models.SmallIntegerField(choices=[(0, 'Not set/inherit'), (1, 'Negative'), (2, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='venue',
            name='contains_loud_music_reasoning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='venue',
            name='contains_low_light',
            field=models.SmallIntegerField(choices=[(0, 'Not set/inherit'), (1, 'Negative'), (2, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='venue',
            name='contains_low_light_reasoning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='venue',
            name='contains_uneven_ground',
            field=models.SmallIntegerField(choices=[(0, 'Not set/inherit'), (1, 'Negative'), (2, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='venue',
            name='contains_uneven_ground_reasoning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='venue',
            name='has_accessible_toilets',
            field=models.SmallIntegerField(choices=[(0, 'Not set/inherit'), (1, 'Negative'), (2, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='venue',
            name='has_accessible_toilets_reasoning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='venue',
            name='has_changing_facilities',
            field=models.SmallIntegerField(choices=[(0, 'Not set/inherit'), (1, 'Negative'), (2, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='venue',
            name='has_changing_facilities_reasoning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='venue',
            name='has_gender_neutral_toilets',
            field=models.SmallIntegerField(choices=[(0, 'Not set/inherit'), (1, 'Negative'), (2, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='venue',
            name='has_gender_neutral_toilets_reasoning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='venue',
            name='has_level_access',
            field=models.SmallIntegerField(choices=[(0, 'Not set/inherit'), (1, 'Negative'), (2, 'Positive')], default=0),
        ),
        migrations.AddField(
            model_name='venue',
            name='has_level_access_reasoning',
            field=models.TextField(blank=True, default=''),
        ),
    ]
