# Generated by Django 2.0.7 on 2018-07-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_auto_20180730_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='canceled_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
