# Generated by Django 2.0.8 on 2018-08-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_auto_20180730_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contains_flashing_lights',
            field=models.SmallIntegerField(choices=[(0, 'Not set/inherit'), (1, 'False'), (2, 'True')], default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='contains_loud_music',
            field=models.SmallIntegerField(choices=[(0, 'Not set/inherit'), (1, 'False'), (2, 'True')], default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='contains_low_light',
            field=models.SmallIntegerField(choices=[(0, 'Not set/inherit'), (1, 'False'), (2, 'True')], default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='contains_uneven_ground',
            field=models.SmallIntegerField(choices=[(0, 'Not set/inherit'), (1, 'False'), (2, 'True')], default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='has_accessible_toilets',
            field=models.SmallIntegerField(choices=[(0, 'Not set/inherit'), (1, 'False'), (2, 'True')], default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='has_changing_facilities',
            field=models.SmallIntegerField(choices=[(0, 'Not set/inherit'), (1, 'False'), (2, 'True')], default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='has_gender_neutral_toilets',
            field=models.SmallIntegerField(choices=[(0, 'Not set/inherit'), (1, 'False'), (2, 'True')], default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='has_level_access',
            field=models.SmallIntegerField(choices=[(0, 'Not set/inherit'), (1, 'False'), (2, 'True')], default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_type',
            field=models.CharField(choices=[('NA', 'n/a'), ('NT', 'Native'), ('EB', 'Eventbrite'), ('MSL', 'MSL')], default='NA', max_length=3),
        ),
        migrations.AlterField(
            model_name='venue',
            name='contains_flashing_lights',
            field=models.SmallIntegerField(choices=[(0, 'Not set/inherit'), (1, 'False'), (2, 'True')], default=0),
        ),
        migrations.AlterField(
            model_name='venue',
            name='contains_loud_music',
            field=models.SmallIntegerField(choices=[(0, 'Not set/inherit'), (1, 'False'), (2, 'True')], default=0),
        ),
        migrations.AlterField(
            model_name='venue',
            name='contains_low_light',
            field=models.SmallIntegerField(choices=[(0, 'Not set/inherit'), (1, 'False'), (2, 'True')], default=0),
        ),
        migrations.AlterField(
            model_name='venue',
            name='contains_uneven_ground',
            field=models.SmallIntegerField(choices=[(0, 'Not set/inherit'), (1, 'False'), (2, 'True')], default=0),
        ),
        migrations.AlterField(
            model_name='venue',
            name='has_accessible_toilets',
            field=models.SmallIntegerField(choices=[(0, 'Not set/inherit'), (1, 'False'), (2, 'True')], default=0),
        ),
        migrations.AlterField(
            model_name='venue',
            name='has_changing_facilities',
            field=models.SmallIntegerField(choices=[(0, 'Not set/inherit'), (1, 'False'), (2, 'True')], default=0),
        ),
        migrations.AlterField(
            model_name='venue',
            name='has_gender_neutral_toilets',
            field=models.SmallIntegerField(choices=[(0, 'Not set/inherit'), (1, 'False'), (2, 'True')], default=0),
        ),
        migrations.AlterField(
            model_name='venue',
            name='has_level_access',
            field=models.SmallIntegerField(choices=[(0, 'Not set/inherit'), (1, 'False'), (2, 'True')], default=0),
        ),
    ]
