# Generated by Django 2.0.8 on 2018-08-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_auto_20180818_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingperiod',
            name='override_listings_root',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
