# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falmer_auth', '0004_auto_20170421_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falmeruser',
            name='authority',
            field=models.CharField(choices=[('IS', 'Internal Staff'), ('MSL', 'MSL Users')], max_length=4),
        ),
    ]
