# Generated by Django 2.0.7 on 2018-07-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falmer_auth', '0005_auto_20180226_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falmeruser',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='falmeruser',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='password'),
        ),
    ]
