# Generated by Django 2.0.2 on 2018-04-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=32, unique=True)),
                ('description', models.TextField(default='')),
                ('state', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('FORCE', 'Force')], default='FORCE', max_length=12)),
                ('expired', models.BooleanField(default=False)),
            ],
        ),
    ]
