# Generated by Django 2.0.2 on 2018-05-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0002_auto_20180419_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='state',
            field=models.BooleanField(default=False, verbose_name='Enabled'),
        ),
    ]
