# Generated by Django 2.2.4 on 2019-09-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_path', models.CharField(db_index=True, max_length=255)),
                ('to_path', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('ABS', 'Absolute'), ('FWD', 'Forward')], default='FWD', max_length=20)),
                ('purpose', models.CharField(choices=[('MARKETING', 'Marketing'), ('LEGACY', 'Legacy')], max_length=20)),
            ],
            options={
                'verbose_name': 'redirect',
                'verbose_name_plural': 'redirects',
                'ordering': ('from_path',),
                'unique_together': {('from_path',)},
            },
        ),
    ]
